theme: jekyll-theme-minimal
icon: /assets/img/icon.png
title: elleen pan
description: |
    <a href="/">home</a> //
    <a href="/resume">resume</a> //
    <a href="https://www.github.com/elleen">github</a>
favicon: /favicon.ico
show_downloads: false
google_analytics: UA-64325333-1
github.is_project_page: false
email_un: hello
email_domain: elleenpan.com
